# Generated by Django 5.0.1 on 2024-02-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "doctors",
                    models.ManyToManyField(
                        blank=True, related_name="specializations", to="doctor.doctor"
                    ),
                ),
            ],
        ),
    ]
